version: '3.6'
services:
  telegraf:
    container_name: telegraf
    image: telegraf:1.22
    restart: on-failure:10
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
      - mosquitto
    ports:
      - '8125:8125/udp'
  influxdb:
    container_name: influxdb
    image: influxdb:2.2
    restart: on-failure:10
    ports:
      - '8086:8086'
    volumes:
      - ./influx/influxdb2:/var/lib/influxdb2
      - ./influx/config.yaml:/etc/influxdb2/influx-config

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.5.2
    restart: on-failure:10
    user: root
    environment:
     - GF_SMTP_ENABLED=true
     - GF_SMTP_HOST=smtp.gmail.com:465
     - GF_SMTP_USER=max0305111@gmail.com
     - GF_SMTP_PASSWORD=R2WQsTPFG
     - GF_SMTP_SKIP_VERIFY=false
     - GF_SMTP_FROM_ADDRESS=max0305111@gmail.ru
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  mosquitto:
     container_name: mosquitto
     image: eclipse-mosquitto:2.0.14
     restart: on-failure:10
     ports:
       - '1883:1883'
     volumes:
       - ./mosquitto/:/mosquitto/config/
